---
title: "Model equations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Model equations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Model equations associated with [Hogan _et al_](https://doi.org/10.1016/j.vaccine.2021.04.002)

# Vaccination group v0 - unvaccinated

$\frac{dS(t,a,v_0)}{dt}=2\rho R_2(t,a,v_0)-\beta\frac{S(t,a,v_0)}{N}\sum_{a\prime}{c(a,a\prime)[\sum_{v}{(I_{MILD}(t,a\prime,v)+I_{CASE}(t,a\prime,v))}}]-κ(a)S(t,a,v0)$
$\frac{dE_1(t,a,v_0)}{dt}=\beta\frac{S(t,a,v_0)}{N}\sum_{a\prime}{c(a,a\prime)[\sum_{v}{(I_{MILD}(t,a\prime,v)+I_{CASE}(t,a\prime,v))}}]-2αE1(t,a,v0)-κ(a)E1(t,a,v0)$
$\frac{dE_2(t,a,v_0)}{dt}=2\alpha E_1(t,a,v_0)-2\alpha E_2(t,a,v_0)-\kappa(a)E_2(t,a,v_0)\frac{dI_{MILD}(t,a,v_0)}{dt}=(1-\phi_1(a))(2\alpha E_2(t,a,v_0))-\gamma_1I_{MILD}(t,a,v_0)$
$\frac{dI_{CASE,0}(t,a,v_0)}{dt}=\phi_1(a)(2\alpha E_2(t,a,v_0))-2\gamma_2I_{CASE,0}(t,a,v_0)$
$\frac{dI_{CASE,1}(t,a,v_0)}{dt}=2\gamma_2I_{CASE,0}(t,a,v_0)-2\gamma_2I_{CASE,1}(t,a,v_0)\frac{dI_{HOSPITAL,0}(t,a,v_0,0,0)}{dt}=(1-\delta(H))\mu(a)(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_0)-2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_0,0,0)$
$\frac{dI_{HOSPITAL,1}(t,a,v_0,0,0)}{dt}=2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_0,0,0)-2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_0,0,0)$
$\frac{dI_{HOSPITAL,0}(t,a,v_0,1,0)}{dt}=\delta(H)\mu(a)(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_0)-2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_0,1,0)$
$\frac{dI_{HOSPITAL,1}(t,a,v_0,1,0)}{dt}=2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_0,1,0)-2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_0,1,0)$
$\frac{dI_{HOSPITAL,0}(t,a,v_0,0,1)}{dt}=(1-\delta(H))(1-\mu(a))(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_0)-2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_0,0,1)$
$\frac{dI_{HOSPITAL,1}(t,a,v_0,0,1)}{dt}=2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_0,0,1)-2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_0,0,1)$
$\frac{dI_{HOSPITAL,0}(t,a,v_0,1,1)}{dt}=\delta(H)(1-\mu(a))(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_0)-2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_0,1,1)$
$\frac{dI_{HOSPITAL,1}(t,a,v_0,1,1)}{dt}=2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_0,1,1)-2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_0,1,1)$
$\frac{dI_{ICU,0}(t,a,v_0,0,0)}{dt}=(1-\delta(ICU))\mu(a)\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_0)-2\gamma_{4,0}I_{ICU,0}(t,a,v_0,0,0)$
$\frac{dI_{ICU,1}(t,a,v_0,0,0)}{dt}=2\gamma_{4,0}I_{ICU,0}(t,a,v_0,0,0)-2\gamma_{4,0}I_{ICU,1}(t,a,v_0,0,0)$
$\frac{dI_{ICU,0}(t,a,v_0,1,0)}{dt}=\delta(ICU)\mu(a)\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_0)-2\gamma_{4,0}I_{ICU,0}(t,a,v_0,1,0)$
$\frac{dI_{ICU,1}(t,a,v_0,1,0)}{dt}=2\gamma_{4,0}I_{ICU,0}(t,a,v_0,1,0)-2\gamma_{4,0}I_{ICU,1}(t,a,v_0,1,0)$
$\frac{dI_{ICU,0}(t,a,v_0,0,1)}{dt}=(1-\delta(ICU))(1-\mu(a))\phi_2(a)2\gamma_2I_{CASE,1}(t,v_0,a)-2\gamma_{4,1}I_{ICU,0}(t,a,v_0,0,1)$
$\frac{dI_{ICU,1}(t,a,v_0,0,1)}{dt}=2\gamma_{4,1}I_{ICU,0}(t,a,v_0,0,1)-2\gamma_{4,1}I_{ICU,1}(t,a,v_0,0,1)$
$\frac{dI_{ICU,0}(t,a,v_0,1,1)}{dt}=\delta(ICU)(1-\mu(a))\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_0)-2\gamma_{4,1}I_{ICU,0}(t,a,v_0,1,1)$
$\frac{dI_{ICU,1}(t,a,v_0,1,1)}{dt}=2\gamma_{4,1}I_{ICU,0}(t,a,v_0,1,1)-2\gamma_{4,1}I_{ICU,1}(t,a,v_0,1,1)$
$\frac{dI_{REC,0}(t,a,v_0)}{dt}=2\gamma_{4,1}I_{ICU,1}(t,a,v_0,0,1)+2γ4,1IICU,1(t,a,v0,1,1)-2γ5IREC,0(t,a,v0)$
$\frac{dI_{REC,1}(t,a,v_0)}{dt}=2\gamma_5I_{REC,0}(t,a,v_0)-2\gamma_5I_{REC,1}(t,a,v_0)$
$\frac{dR_1(t,a,v_0)}{dt}=\gamma_1I_{MILD}(t,a,v_0)+2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_0,0,1)+2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_0,1,1)+2\gamma_5I_{REC,1}(t,a,v_0)+2\gamma_{4,1}I_{ICU,1}(t,a,v_0,0,1)+2\gamma_{4,1}I_{ICU,1}(t,a,v_0,1,1)-2\rho R_1(t,a,v_0)-\kappa(a)R_1(t,a,v_0)$
$\frac{dR_2(t,a,v_0)}{dt}=2\rho R_1(t,a,v_0)-2\rho R_2(t,a,v_0)-\kappa(a)R_2(t,a,v_0)$
$\frac{dD(t,a,v_0)}{dt}=2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_0,0,0)+2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_0,1,0)+2\gamma_{4,0}I_{ICU,1}(t,a,v_0,0,0)+2\gamma_{4,0}I_{ICU,1}(t,a,v_0,1,0)$

# Vaccination group v1 - vaccinated but not yet protected (state 1)

$\frac{dS(t,a,v_1)}{dt}=\kappa(a)S(t,a,v_0)+2\rho R_2(t,a,v_1)-\beta\frac{S(t,a,v_1)}{N}\sum_{a\prime}{c(a,a\prime)[\sum_{v}{(I_{MILD}(t,a\prime,v)+I_{CASE}(t,a\prime,v))}}]-2ωS(t,a,v1)$
$\frac{dE_1(t,a,v_1)}{dt}=\kappa(a)E_1(t,a,v_0)+βS(t,a,v1)Na'c(a,a')[v(IMILD(t,a',v)+ICASE(t,a',v))]-2αE1(t,a,v1)-2ωE1(t,a,v1)$
$\frac{dE_2(t,a,v_1)}{dt}=\kappa(a)E_2(t,a,v_0)+2\alpha E_1(t,a,v_1)-2\alpha E_2(t,a,v_1)-2\omega E_2(t,a,v_1)$   
$\frac{dI_{MILD}(t,a,v_1)}{dt}=(1-\phi_1(a))(2\alpha E_2(t,a,v_1))-\gamma_1I_{MILD}(t,a,v_1)-2\omega I_{MILD}(t,a,v_1)$   
$\frac{dI_{CASE,0}(t,a,v_1)}{dt}=\phi_1(a)(2\alpha E_2(t,a,v_1))-2\gamma_2I_{CASE,0}(t,a,v_1)-2\omega I_{CASE,0}(t,a,v_1)$   
$\frac{dI_{CASE,1}(t,a,v_1)}{dt}=2\gamma_2I_{CASE,0}(t,a,v_1)-2\gamma_2I_{CASE,1}(t,a,v_1)-2\omega I_{CASE,1}(t,a,v_1)$   $\frac{dI_{HOSPITAL,0}(t,a,v_1,0,0)}{dt}=(1-\delta(H))\mu(a)(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_1)-2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_1,0,0)-2\omega I_{HOSPITAL,0}(t,a,v_1,0,0)$   $\frac{dI_{HOSPITAL,1}(t,a,v_1,0,0)}{dt}=2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_1,0,0)-2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_1,0,0)-2\omega I_{HOSPITAL,1}(t,a,v_1,0,0)$   $\frac{dI_{HOSPITAL,0}(t,a,v_1,1,0)}{dt}=\delta(H)\mu(a)(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_1)-2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_1,1,0)-2\omega I_{HOSPITAL,0}(t,a,v_1,1,0)$   $\frac{dI_{HOSPITAL,1}(t,a,v_1,1,0)}{dt}=2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_1,1,0)-2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_1,1,0)-2\omega I_{HOSPITAL,1}(t,a,v_1,1,0)$   $\frac{dI_{HOSPITAL,0}(t,a,v_1,0,1)}{dt}=(1-\delta(H))(1-\mu(a))(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_1)-2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_1,0,1)-2\omega I_{HOSPITAL,0}(t,a,v_1,0,1)$   $\frac{dI_{HOSPITAL,1}(t,a,v_1,0,1)}{dt}=2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_1,0,1)-2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_1,0,1)-2\omega I_{HOSPITAL,1}(t,a,v_1,0,1)$   $\frac{dI_{HOSPITAL,0}(t,a,v_1,1,1)}{dt}=\delta(H)(1-\mu(a))(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_1)-2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_1,1,1)-2\omega I_{HOSPITAL,0}(t,a,v_1,1,1)$   $\frac{dI_{HOSPITAL,1}(t,a,v_1,1,1)}{dt}=2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_1,1,1)-2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_1,1,1)-2\omega I_{HOSPITAL,1}(t,a,v_1,1,1)$   $\frac{dI_{ICU,0}(t,a,v_1,0,0)}{dt}=(1-\delta(ICU))\mu(a)\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_1)-2\gamma_{4,0}I_{ICU,0}(t,a,v_1,0,0)-2\omega I_{ICU,0}(t,a,v_1,0,0)$   $\frac{dI_{ICU,1}(t,a,v_1,0,0)}{dt}=2\gamma_{4,0}I_{ICU,0}(t,a,v_1,0,0)-2\gamma_{4,0}I_{ICU,1}(t,a,v_1,0,0)-2\omega I_{ICU,1}(t,a,v_1,0,0)$   $\frac{dI_{ICU,0}(t,a,v_1,1,0)}{dt}=\delta(ICU)\mu(a)\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_1)-2\gamma_{4,0}I_{ICU,0}(t,a,v_1,1,0)-2\omega I_{ICU,0}(t,a,v_1,1,0)$   $\frac{dI_{ICU,1}(t,a,v_1,1,0)}{dt}=2\gamma_{4,0}I_{ICU,0}(t,a,v_1,1,0)-2\gamma_{4,0}I_{ICU,1}(t,a,v_1,1,0)-2\omega I_{ICU,1}(t,a,v_1,1,0)$   $\frac{dI_{ICU,0}(t,a,v_1,0,1)}{dt}=(1-\delta(ICU))(1-\mu(a))\phi_2(a)2\gamma_2I_{CASE,1}(t,v_1,a)-2\gamma_{4,1}I_{ICU,0}(t,a,v_1,0,1)-2\omega I_{ICU,0}(t,a,v_1,0,1)$   $\frac{dI_{ICU,1}(t,a,v_1,0,1)}{dt}=2\gamma_{4,1}I_{ICU,0}(t,a,v_1,0,1)-2\gamma_{4,1}I_{ICU,1}(t,a,v_1,0,1)-2\omega I_{ICU,1}(t,a,v_1,0,1)$   $\frac{dI_{ICU,0}(t,a,v_1,1,1)}{dt}=\delta(ICU)(1-\mu(a))\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_1)-2\gamma_{4,1}I_{ICU,0}(t,a,v_1,1,1)-2\omega I_{ICU,0}(t,a,v_1,1,1)$   $\frac{dI_{ICU,1}(t,a,v_1,1,1)}{dt}=2\gamma_{4,1}I_{ICU,0}(t,a,v_1,1,1)-2\gamma_{4,1}I_{ICU,1}(t,a,v_1,1,1)-2\omega I_{ICU,1}(t,a,v_1,1,1)$   $\frac{dI_{REC,0}(t,a,v_1)}{dt}=2\gamma_{4,1}I_{ICU,1}(t,a,v_1,0,1)+2\gamma_{4,1}I_{ICU,1}(t,a,v_1,1,1)-2\gamma_5I_{REC,0}(t,a,v_1)-2\omega I_{REC,0}(t,a,v_1)$   $\frac{dI_{REC,1}(t,a,v_1)}{dt}=2\gamma_5I_{REC,0}(t,a,v_1)-2\gamma_5I_{REC,1}(t,a,v_1)-2\omega I_{REC,1}(t,a,v_1)$   $\frac{dR_1(t,a,v_1)}{dt}=\kappa(a)R_1(t,a,v_0)+\gamma_1I_{MILD}(t,a,v_1)+2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_1,0,1)+2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_1,1,1)+2\gamma_5I_{REC,1}(t,a,v_1)+2\gamma_{4,1}I_{ICU,1}(t,a,v_1,0,1)+2\gamma_{4,1}I_{ICU,1}(t,a,v_1,1,1)-2\rho R_1(t,a,v_1)-2\omega R(t,a,v_1)$   
$\frac{dR_2(t,a,v_1)}{dt}=\kappa(a)R_2(t,a,v_0)+2\rho R_1(t,a,v_1)-2\rho R_2(t,a,v_1)$   $\frac{dD(t,a,v_1)}{dt}=2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_1,0,0)+2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_1,1,0)+2\gamma_{4,0}I_{ICU,1}(t,a,v_1,0,0)+2\gamma_{4,0}I_{ICU,1}(t,a,v_1,1,0)$

# Vaccination group v2 - vaccinated but not yet protected (state 2)

$\frac{dS(t,a,v_2)}{dt}=2\rho R_2(t,a,v_2)-\beta\frac{S(t,a,v_2)}{N}\sum_{a\prime}{c(a,a\prime)[\sum_{v}{(I_{MILD}(t,a\prime,v)+I_{CASE}(t,a\prime,v))}}]+2ωS(t,a,v1)-2ωS(t,a,v2)$
$\frac{dE_1(t,a,v_2)}{dt}=\beta\frac{S(t,a,v_2)}{N}\sum_{a\prime}{c(a,a\prime)[\sum_{v}{(I_{MILD}(t,a\prime,v)+I_{CASE}(t,a\prime,v))}}]-2αE1(t,a,v2)+2ωE1(t,a,v1)-2ωE1(t,a,v2)$
$\frac{dE_2(t,a,v_2)}{dt}=2\alpha E_1(t,a,v_2)-2\alpha E_2(t,a,v_2)+2\omega E_2(t,a,v_1)-2\omega E_2(t,a,v_2)$   
$\frac{dI_{MILD}(t,a,v_2)}{dt}=(1-\phi_1(a))(2\alpha E_2(t,a,v_2))-\gamma_1I_{MILD}(t,a,v_2)+2\omega I_{MILD}(t,a,v_1)-2\omega I_{MILD}(t,a,v_2)$   
$\frac{dI_{CASE,0}(t,a,v_2)}{dt}=\phi_1(a)(2\alpha E_2(t,a,v_2))-2\gamma_2I_{CASE,0}(t,a,v_2)+2\omega I_{CASE,0}(t,a,v_1)-2\omega I_{CASE,0}(t,a,v_2)$   
$\frac{dI_{CASE,1}(t,a,v_2)}{dt}=2\gamma_2I_{CASE,0}(t,a,v_2)-2\gamma_2I_{CASE,1}(t,a,v_2)+2\omega I_{CASE,1}(t,a,v_1)-2\omega I_{CASE,1}(t,a,v_2)$   $\frac{dI_{HOSPITAL,0}(t,a,v_2,0,0)}{dt}=(1-\delta(H))\mu(a)(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_2)-2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_2,0,0)+2\omega I_{HOSPITAL,0}(t,a,v_1,0,0)-2\omega I_{HOSPITAL,0}(t,a,v_2,0,0)$   $\frac{dI_{HOSPITAL,1}(t,a,v_2,0,0)}{dt}=2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_2,0,0)-2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_2,0,0)+2\omega I_{HOSPITAL,1}(t,a,v_1,0,0)-2\omega I_{HOSPITAL,1}(t,a,v_2,0,0)$   $\frac{dI_{HOSPITAL,0}(t,a,v_2,1,0)}{dt}=\delta(H)\mu(a)(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_2)-2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_2,1,0)+2\omega I_{HOSPITAL,0}(t,a,v_1,1,0)-2\omega I_{HOSPITAL,0}(t,a,v_2,1,0)$   $\frac{dI_{HOSPITAL,1}(t,a,v_2,1,0)}{dt}=2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_2,1,0)-2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_2,1,0)+2\omega I_{HOSPITAL,1}(t,a,v_1,1,0)-2\omega I_{HOSPITAL,1}(t,a,v_2,1,0)$   $\frac{dI_{HOSPITAL,0}(t,a,v_2,0,1)}{dt}=(1-\delta(H))(1-\mu(a))(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_2)-2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_2,0,1)+2\omega I_{HOSPITAL,0}(t,a,v_1,0,1)-2\omega I_{HOSPITAL,0}(t,a,v_2,0,1)$   $\frac{dI_{HOSPITAL,1}(t,a,v_2,0,1)}{dt}=2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_2,0,1)-2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_2,0,1)+2\omega I_{HOSPITAL,1}(t,a,v_1,0,1)-2\omega I_{HOSPITAL,1}(t,a,v_2,0,1)$   $\frac{dI_{HOSPITAL,0}(t,a,v_2,1,1)}{dt}=\delta(H)(1-\mu(a))(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_2)-2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_2,1,1)+2\omega I_{HOSPITAL,0}(t,a,v_1,1,1)-2\omega I_{HOSPITAL,0}(t,a,v_2,1,1)$   $\frac{dI_{HOSPITAL,1}(t,a,v_2,1,1)}{dt}=2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_2,1,1)-2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_2,1,1)+2\omega I_{HOSPITAL,1}(t,a,v_1,1,1)-2\omega I_{HOSPITAL,1}(t,a,v_2,1,1)$   $\frac{dI_{ICU,0}(t,a,v_2,0,0)}{dt}=(1-\delta(ICU))\mu(a)\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_2)-2\gamma_{4,0}I_{ICU,0}(t,a,v_2,0,0)+2\omega I_{ICU,0}(t,a,v_1,0,0)-2\omega I_{ICU,0}(t,a,v_2,0,0)$   $\frac{dI_{ICU,1}(t,a,v_2,0,0)}{dt}=2\gamma_{4,0}I_{ICU,0}(t,a,v_2,0,0)-2\gamma_{4,0}I_{ICU,1}(t,a,v_2,0,0)+2\omega I_{ICU,1}(t,a,v_1,0,0)-2\omega I_{ICU,1}(t,a,v_2,0,0)$   $\frac{dI_{ICU,0}(t,a,v_2,1,0)}{dt}=\delta(ICU)\mu(a)\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_2)-2\gamma_{4,0}I_{ICU,0}(t,a,v_2,1,0)+2\omega I_{ICU,0}(t,a,v_1,1,0)-2\omega I_{ICU,0}(t,a,v_2,1,0)$   $\frac{dI_{ICU,1}(t,a,v_2,1,0)}{dt}=2\gamma_{4,0}I_{ICU,0}(t,a,v_2,1,0)-2\gamma_{4,0}I_{ICU,1}(t,a,v_2,1,0)+2\omega I_{ICU,1}(t,a,v_1,1,0)-2\omega I_{ICU,1}(t,a,v_2,1,0)$   $\frac{dI_{ICU,0}(t,a,v_2,0,1)}{dt}=(1-\delta(ICU))(1-\mu(a))\phi_2(a)2\gamma_2I_{CASE,1}(t,v_2,a)-2\gamma_{4,1}I_{ICU,0}(t,a,v_2,0,1)+2\omega I_{ICU,0}(t,a,v_1,0,1)-2\omega I_{ICU,0}(t,a,v_2,0,1)$   $\frac{dI_{ICU,1}(t,a,v_2,0,1)}{dt}=2\gamma_{4,1}I_{ICU,0}(t,a,v_2,0,1)-2\gamma_{4,1}I_{ICU,1}(t,a,v_2,0,1)+2\omega I_{ICU,1}(t,a,v_1,0,1)-2\omega I_{ICU,1}(t,a,v_2,0,1)$   $\frac{dI_{ICU,0}(t,a,v_2,1,1)}{dt}=\delta(ICU)(1-\mu(a))\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_2)-2\gamma_{4,1}I_{ICU,0}(t,a,v_2,1,1)+2\omega I_{ICU,0}(t,a,v_1,1,1)-2\omega I_{ICU,0}(t,a,v_2,1,1)$   $\frac{dI_{ICU,1}(t,a,v_2,1,1)}{dt}=2\gamma_{4,1}I_{ICU,0}(t,a,v_2,1,1)-2\gamma_{4,1}I_{ICU,1}(t,a,v_2,1,1)+2\omega I_{ICU,1}(t,a,v_1,1,1)-2\omega I_{ICU,1}(t,a,v_2,1,1)$   $\frac{dI_{REC,0}(t,a,v_2)}{dt}=2\gamma_{4,1}I_{ICU,1}(t,a,v_2,0,1)+2\gamma_{4,1}I_{ICU,1}(t,a,v_2,1,1)-2\gamma_5I_{REC,0}(t,a,v_2)+2\omega I_{REC,0}(t,a,v_1)-2\omega I_{REC,0}(t,a,v_2)$   $\frac{dI_{REC,1}(t,a,v_2)}{dt}=2\gamma_5I_{REC,0}(t,a,v_2)-2\gamma_5I_{REC,1}(t,a,v_2)+2\omega I_{REC,1}(t,a,v_1)-2\omega I_{REC,1}(t,a,v_2)$   $\frac{dR_1(t,a,v_2)}{dt}=\gamma_1I_{MILD}(t,a,v_2)+2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_2,0,1)+2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_2,1,1)+2\gamma_5I_{REC,1}(t,a,v_2)+2\gamma_{4,1}I_{ICU,1}(t,a,v_2,0,1)+2\gamma_{4,1}I_{ICU,1}(t,a,v_2,1,1)-2\rho R_1(t,a,v_2)+2\omega R_1(t,a,v_1)-2\omega R_1(t,a,v_2)$   
$\frac{dR_2(t,a,v_2)}{dt}=2\rho R_1(t,a,v_2)-2\rho R_2(t,a,v_2)+2\omega R_2(t,a,v_1)-2\omega R_2(t,a,v_2)$   $\frac{dD(t,a,v_2)}{dt}=2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_2,0,0)+2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_2,1,0)+2\gamma_{4,0}I_{ICU,1}(t,a,v_2,0,0)+2\gamma_{4,0}I_{ICU,1}(t,a,v_2,1,0)$

# Vaccination group v3 - vaccinated and protected (state 1)

$\frac{dS(t,a,v_3)}{dt}=2\rho R_2(t,a,v_3)-\upsilon_{inf}\left(a\right)\beta\frac{S\left(t,a,v_3\right)}{N}\sum_{a^\prime}{c(a,a\prime)[\sum_{v}\left(I_{MILD}\left(t,a^\prime,v\right)+I_{CASE}\left(t,a^\prime,v\right)\right)}]+2ωS(t,a,v2)-2ψS(t,a,v3)$ 
$\frac{dE_1(t,a,v_3)}{dt}=\upsilon_{inf}\left(a\right)\beta\frac{S(t,a,v_3)}{N}\sum_{a\prime}{c(a,a\prime)[\sum_{v}{(I_{MILD}(t,a\prime,v)+I_{CASE}(t,a\prime,v))}}]-2αE1(t,a,v2)+2ωE1(t,a,v2)-2ψE1(t,a,v3)$
$\frac{dE_2(t,a,v_3)}{dt}=2\alpha E_1(t,a,v_3)-2\alpha E_2(t,a,v_3)+2\omega E_2(t,a,v_2)-2\psi E_2(t,a,v_3)$   
$\frac{dI_{MILD}(t,a,v_3)}{dt}=(1-\upsilon_{dis}(a)\phi_1(a))(2\alpha E_2(t,a,v_3))-\gamma_1I_{MILD}(t,a,v_3)+2\omega I_{MILD}(t,a,v_2)-2\psi I_{MILD}(t,a,v_3)$   
$\frac{dI_{CASE,0}(t,a,v_3)}{dt}=\upsilon_{dis}(a)\phi_1(a)(2\alpha E_2(t,a,v_3))-2\gamma_2I_{CASE,0}(t,a,v_3)+2\omega I_{CASE,0}(t,a,v_2)-2\psi I_{CASE,0}(t,a,v_3)$   $\frac{dI_{CASE,1}(t,a,v_3)}{dt}=2\gamma_2I_{CASE,0}(t,a,v_3)-2\gamma_2I_{CASE,1}(t,a,v_3)+2\omega I_{CASE,1}(t,a,v_2)-2\psi I_{CASE,1}(t,a,v_3)$   $\frac{dI_{HOSPITAL,0}(t,a,v_3,0,0)}{dt}=(1-\delta(H))\mu(a)(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_3)-2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_3,0,0)+2\omega I_{HOSPITAL,0}(t,a,v_2,0,0)-2\psi I_{HOSPITAL,0}(t,a,v_3,0,0)$   $\frac{dI_{HOSPITAL,1}(t,a,v_3,0,0)}{dt}=2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_3,0,0)-2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_3,0,0)+2\omega I_{HOSPITAL,1}(t,a,v_2,0,0)-2\psi I_{HOSPITAL,1}(t,a,v_3,0,0)$   $\frac{dI_{HOSPITAL,0}(t,a,v_3,1,0)}{dt}=\delta(H)\mu(a)(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_3)-2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_3,1,0)+2\omega I_{HOSPITAL,0}(t,a,v_2,1,0)-2\psi I_{HOSPITAL,0}(t,a,v_3,1,0)$   $\frac{dI_{HOSPITAL,1}(t,a,v_3,1,0)}{dt}=2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_3,1,0)-2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_3,1,0)+2\omega I_{HOSPITAL,1}(t,a,v_2,1,0)-2\psi I_{HOSPITAL,1}(t,a,v_3,1,0)$   $\frac{dI_{HOSPITAL,0}(t,a,v_3,0,1)}{dt}=(1-\delta(H))(1-\mu(a))(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_3)-2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_3,0,1)+2\omega I_{HOSPITAL,0}(t,a,v_2,0,1)-2\psi I_{HOSPITAL,0}(t,a,v_3,0,1)$   $\frac{dI_{HOSPITAL,1}(t,a,v_3,0,1)}{dt}=2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_3,0,1)-2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_3,0,1)+2\omega I_{HOSPITAL,1}(t,a,v_2,0,1)-2\psi I_{HOSPITAL,1}(t,a,v_3,0,1)$   $\frac{dI_{HOSPITAL,0}(t,a,v_3,1,1)}{dt}=\delta(H)(1-\mu(a))(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_3)-2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_3,1,1)+2\omega I_{HOSPITAL,0}(t,a,v_2,1,1)-2\psi I_{HOSPITAL,0}(t,a,v_3,1,1)$   $\frac{dI_{HOSPITAL,1}(t,a,v_3,1,1)}{dt}=2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_3,1,1)-2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_3,1,1)+2\omega I_{HOSPITAL,1}(t,a,v_2,1,1)-2\psi I_{HOSPITAL,1}(t,a,v_3,1,1)$   $\frac{dI_{ICU,0}(t,a,v_3,0,0)}{dt}=(1-\delta(ICU))\mu(a)\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_3)-2\gamma_{4,0}I_{ICU,0}(t,a,v_3,0,0)+2\omega I_{ICU,0}(t,a,v_2,0,0)-2\psi I_{ICU,0}(t,a,v_3,0,0)$   $\frac{dI_{ICU,1}(t,a,v_3,0,0)}{dt}=2\gamma_{4,0}I_{ICU,0}(t,a,v_3,0,0)-2\gamma_{4,0}I_{ICU,1}(t,a,v_3,0,0)+2\omega I_{ICU,1}(t,a,v_2,0,0)-2\psi I_{ICU,1}(t,a,v_3,0,0)$   $\frac{dI_{ICU,0}(t,a,v_3,1,0)}{dt}=\delta(ICU)\mu(a)\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_3)-2\gamma_{4,0}I_{ICU,0}(t,a,v_3,1,0)+2\omega I_{ICU,0}(t,a,v_2,1,0)-2\psi I_{ICU,0}(t,a,v_3,1,0)$   $\frac{dI_{ICU,1}(t,a,v_3,1,0)}{dt}=2\gamma_{4,0}I_{ICU,0}(t,a,v_3,1,0)-2\gamma_{4,0}I_{ICU,1}(t,a,v_3,1,0)+2\omega I_{ICU,1}(t,a,v_2,1,0)-2\psi I_{ICU,1}(t,a,v_3,1,0)$   $\frac{dI_{ICU,0}(t,a,v_3,0,1)}{dt}=(1-\delta(ICU))(1-\mu(a))\phi_2(a)2\gamma_2I_{CASE,1}(t,v_3,a)-2\gamma_{4,1}I_{ICU,0}(t,a,v_3,0,1)+2\omega I_{ICU,0}(t,a,v_2,0,1)-2\psi I_{ICU,0}(t,a,v_3,0,1)$   $\frac{dI_{ICU,1}(t,a,v_3,0,1)}{dt}=2\gamma_{4,1}I_{ICU,0}(t,a,v_3,0,1)-2\gamma_{4,1}I_{ICU,1}(t,a,v_3,0,1)+2\omega I_{ICU,1}(t,a,v_2,0,1)-2\psi I_{ICU,1}(t,a,v_3,0,1)$   $\frac{dI_{ICU,0}(t,a,v_3,1,1)}{dt}=\delta(ICU)(1-\mu(a))\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_3)-2\gamma_{4,1}I_{ICU,0}(t,a,v_3,1,1)+2\omega I_{ICU,0}(t,a,v_2,1,1)-2\psi I_{ICU,0}(t,a,v_3,1,1)$   $\frac{dI_{ICU,1}(t,a,v_3,1,1)}{dt}=2\gamma_{4,1}I_{ICU,0}(t,a,v_3,1,1)-2\gamma_{4,1}I_{ICU,1}(t,a,v_3,1,1)+2\omega I_{ICU,1}(t,a,v_2,1,1)-2\psi I_{ICU,1}(t,a,v_3,1,1)$   $\frac{dI_{REC,0}(t,a,v_3)}{dt}=2\gamma_{4,1}I_{ICU,1}(t,a,v_3,0,1)+2\gamma_{4,1}I_{ICU,1}(t,a,v_3,1,1)-2\gamma_5I_{REC,0}(t,a,v_3)+2\omega I_{REC,0}(t,a,v_2)-2\psi I_{REC,0}(t,a,v_3)$   $\frac{dI_{REC,1}(t,a,v_3)}{dt}=2\gamma_5I_{REC,0}(t,a,v_3)-2\gamma_5I_{REC,1}(t,a,v_3)+2\omega I_{REC,1}(t,a,v_2)-2\psi I_{REC,1}(t,a,v_3)$   $\frac{dR_1(t,a,v_3)}{dt}=\gamma_1I_{MILD}(t,a,v_3)+2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_3,0,1)+2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_3,1,1)+2\gamma_5I_{REC,1}(t,a,v_3)+2\gamma_{4,1}I_{ICU,1}(t,a,v_3,0,1)+2\gamma_{4,1}I_{ICU,1}(t,a,v_3,1,1)-2\rho R_1(t,a,v_3)+2\omega R_1(t,a,v_2)-2\psi R_1(t,a,v_3)$   
$\frac{dR_2(t,a,v_3)}{dt}=2\rho R_1(t,a,v_3)-2\rho R_2(t,a,v_3)+2\omega R_2(t,a,v_2)-2\psi R_2(t,a,v_3)$   $\frac{dD(t,a,v_3)}{dt}=2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_3,0,0)+2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_3,1,0)+2\gamma_{4,0}I_{ICU,1}(t,a,v_3,0,0)+2\gamma_{4,0}I_{ICU,1}(t,a,v_3,1,0)$

# Vaccination group v4 - vaccinated and protected (state 2)

$\frac{dS(t,a,v_4)}{dt}=2\rho R_2(t,a,v_4)-\upsilon_{inf}\left(a\right)\beta\frac{S\left(t,a,v_4\right)}{N}\sum_{a^\prime}{c(a,a\prime)[\sum_{v}\left(I_{MILD}\left(t,a^\prime,v\right)+I_{CASE}\left(t,a^\prime,v\right)\right)}]+2ψS(t,a,v3)-2ψS(t,a,v4)$ $\frac{dE_1(t,a,v_4)}{dt}=\upsilon_{inf}\left(a\right)\beta\frac{S(t,a,v_4)}{N}\sum_{a\prime}{c(a,a\prime)[\sum_{v}{(I_{MILD}(t,a\prime,v)+I_{CASE}(t,a\prime,v))}}]-2αE1(t,a,v4)+2ψE1(t,a,v3)-2ψE1(t,a,v4)$   
$\frac{dE_2(t,a,v_4)}{dt}=2\alpha E_1(t,a,v_4)-2\alpha E_2(t,a,v_4)+2\psi E_2(t,a,v_3)-2\psi E_2(t,a,v_4)$   
$\frac{dI_{MILD}(t,a,v_4)}{dt}=(1-\upsilon_{dis}(a)\phi_1(a))(2\alpha E_2(t,a,v_4))-\gamma_1I_{MILD}(t,a,v_4)+2\psi I_{MILD}(t,a,v_3)-2\psi I_{MILD}(t,a,v_4)$   
$\frac{dI_{CASE,0}(t,a,v_4)}{dt}=\upsilon_{dis}(a)\phi_1(a)(2\alpha E_2(t,a,v_4))-2\gamma_2I_{CASE,0}(t,a,v_4)+2\psi I_{CASE,0}(t,a,v_3)-2\psi I_{CASE,0}(t,a,v_4)$   $\frac{dI_{CASE,1}(t,a,v_4)}{dt}=2\gamma_2I_{CASE,0}(t,a,v_4)-2\gamma_2I_{CASE,1}(t,a,v_4)+2\psi I_{CASE,1}(t,a,v_3)-2\psi I_{CASE,1}(t,a,v_4)$   $\frac{dI_{HOSPITAL,0}(t,a,v_4,0,0)}{dt}=(1-\delta(H))\mu(a)(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_4)-2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_4,0,0)+2\psi I_{HOSPITAL,0}(t,a,v_3,0,0)-2\psi I_{HOSPITAL,0}(t,a,v_4,0,0)$   $\frac{dI_{HOSPITAL,1}(t,a,v_4,0,0)}{dt}=2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_4,0,0)-2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_4,0,0)+2\psi I_{HOSPITAL,1}(t,a,v_3,0,0)-2\psi I_{HOSPITAL,1}(t,a,v_4,0,0)$   $\frac{dI_{HOSPITAL,0}(t,a,v_4,1,0)}{dt}=\delta(H)\mu(a)(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_4)-2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_4,1,0)+2\psi I_{HOSPITAL,0}(t,a,v_3,1,0)-2\psi I_{HOSPITAL,0}(t,a,v_3,1,0)$   $\frac{dI_{HOSPITAL,1}(t,a,v_4,1,0)}{dt}=2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_4,1,0)-2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_4,1,0)+2\psi I_{HOSPITAL,1}(t,a,v_3,1,0)-2\psi I_{HOSPITAL,1}(t,a,v_4,1,0)$   $\frac{dI_{HOSPITAL,0}(t,a,v_4,0,1)}{dt}=(1-\delta(H))(1-\mu(a))(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_4)-2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_4,0,1)+2\psi I_{HOSPITAL,0}(t,a,v_3,0,1)-2\psi I_{HOSPITAL,0}(t,a,v_4,0,1)$   $\frac{dI_{HOSPITAL,1}(t,a,v_4,0,1)}{dt}=2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_4,0,1)-2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_4,0,1)+2\psi I_{HOSPITAL,1}(t,a,v_3,0,1)-2\psi I_{HOSPITAL,1}(t,a,v_4,0,1)$   $\frac{dI_{HOSPITAL,0}(t,a,v_4,1,1)}{dt}=\delta(H)(1-\mu(a))(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_4)-2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_4,1,1)+2\psi I_{HOSPITAL,0}(t,a,v_3,1,1)-2\psi I_{HOSPITAL,0}(t,a,v_4,1,1)$   $\frac{dI_{HOSPITAL,1}(t,a,v_4,1,1)}{dt}=2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_4,1,1)-2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_4,1,1)+2\psi I_{HOSPITAL,1}(t,a,v_3,1,1)-2\psi I_{HOSPITAL,1}(t,a,v_4,1,1)$   $\frac{dI_{ICU,0}(t,a,v_4,0,0)}{dt}=(1-\delta(ICU))\mu(a)\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_4)-2\gamma_{4,0}I_{ICU,0}(t,a,v_4,0,0)+2\psi I_{ICU,0}(t,a,v_3,0,0)-2\psi I_{ICU,0}(t,a,v_4,0,0)$   $\frac{dI_{ICU,1}(t,a,v_4,0,0)}{dt}=2\gamma_{4,0}I_{ICU,0}(t,a,v_4,0,0)-2\gamma_{4,0}I_{ICU,1}(t,a,v_4,0,0)+2\psi I_{ICU,1}(t,a,v_3,0,0)-2\psi I_{ICU,1}(t,a,v_4,0,0)$   $\frac{dI_{ICU,0}(t,a,v_4,1,0)}{dt}=\delta(ICU)\mu(a)\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_4)-2\gamma_{4,0}I_{ICU,0}(t,a,v_4,1,0)+2\psi I_{ICU,0}(t,a,v_3,1,0)-2\psi I_{ICU,0}(t,a,v_4,1,0)$   $\frac{dI_{ICU,1}(t,a,v_4,1,0)}{dt}=2\gamma_{4,0}I_{ICU,0}(t,a,v_4,1,0)-2\gamma_{4,0}I_{ICU,1}(t,a,v_4,1,0)+2\psi I_{ICU,1}(t,a,v_3,1,0)-2\psi I_{ICU,1}(t,a,v_4,1,0)$   $\frac{dI_{ICU,0}(t,a,v_4,0,1)}{dt}=(1-\delta(ICU))(1-\mu(a))\phi_2(a)2\gamma_2I_{CASE,1}(t,v_4,a)-2\gamma_{4,1}I_{ICU,0}(t,a,v_4,0,1)+2\psi I_{ICU,0}(t,a,v_3,0,1)-2\psi I_{ICU,0}(t,a,v_4,0,1)$   $\frac{dI_{ICU,1}(t,a,v_4,0,1)}{dt}=2\gamma_{4,1}I_{ICU,0}(t,a,v_4,0,1)-2\gamma_{4,1}I_{ICU,1}(t,a,v_4,0,1)+2\psi I_{ICU,1}(t,a,v_3,0,1)-2\psi I_{ICU,1}(t,a,v_4,0,1)$   $\frac{dI_{ICU,0}(t,a,v_4,1,1)}{dt}=\delta(ICU)(1-\mu(a))\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_4)-2\gamma_{4,1}I_{ICU,0}(t,a,v_4,1,1)+2\psi I_{ICU,0}(t,a,v_3,1,1)-2\psi I_{ICU,0}(t,a,v_4,1,1)$   $\frac{dI_{ICU,1}(t,a,v_4,1,1)}{dt}=2\gamma_{4,1}I_{ICU,0}(t,a,v_4,1,1)-2\gamma_{4,1}I_{ICU,1}(t,a,v_4,1,1)+2\psi I_{ICU,1}(t,a,v_3,1,1)-2\psi I_{ICU,1}(t,a,v_4,1,1)$   $\frac{dI_{REC,0}(t,a,v_4)}{dt}=2\gamma_{4,1}I_{ICU,1}(t,a,v_4,0,1)+2\gamma_{4,1}I_{ICU,1}(t,a,v_4,1,1)-2\gamma_5I_{REC,0}(t,a,v_4)+2\psi I_{REC,0}(t,a,v_3)-2\psi I_{REC,0}(t,a,v_4)$   $\frac{dI_{REC,1}(t,a,v_4)}{dt}=2\gamma_5I_{REC,0}(t,a,v_4)-2\gamma_5I_{REC,1}(t,a,v_4)+2\psi I_{REC,1}(t,a,v_3)-2\psi I_{REC,1}(t,a,v_4)$   $\frac{dR_1(t,a,v_4)}{dt}=\gamma_1I_{MILD}(t,a,v_4)+2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_4,0,1)+2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_4,1,1)+2\gamma_5I_{REC,1}(t,a,v_4)+2\gamma_{4,1}I_{ICU,1}(t,a,v_4,0,1)+2\gamma_{4,1}I_{ICU,1}(t,a,v_4,1,1)-2\rho R_1(t,a,v_4)+2\psi R_1(t,a,v_3)-2\psi R_1(t,a,v_4)$   
$\frac{dR_2(t,a,v_4)}{dt}=2\rho R_1(t,a,v_4)-2\rho R_2(t,a,v_4)+2\psi R_2(t,a,v_3)-2\psi R_2(t,a,v_4)$   $\frac{dD(t,a,v_4)}{dt}=2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_4,0,0)+2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_4,1,0)+2\gamma_{4,0}I_{ICU,1}(t,a,v_4,0,0)+2\gamma_{4,0}I_{ICU,1}(t,a,v_4,1,0)$

# Vaccination group v5 - previously vaccinated but no longer protected

$\frac{dS(t,a,v_5)}{dt}=2\rho R_2(t,a,v_5)-\beta\frac{S(t,a,v_5)}{N}\sum_{a\prime}{c(a,a\prime)[\sum_{v}{(I_{MILD}(t,a\prime,v)+I_{CASE}(t,a\prime,v))}}]+2ψS(t,a,v4)$
$\frac{dE_1(t,a,v_5)}{dt}=\beta\frac{S(t,a,v_5)}{N}\sum_{a\prime}{c(a,a\prime)[\sum_{v}{(I_{MILD}(t,a\prime,v)+I_{CASE}(t,a\prime,v))}}]-2αE1(t,a,v5)+2ψE1(t,a,v4)$
$\frac{dE_2(t,a,v_5)}{dt}=2\alpha E_1(t,a,v_5)-2\alpha E_2(t,a,v_5)+2\psi E_2(t,a,v_4)$   
$\frac{dI_{MILD}(t,a,v_5)}{dt}=(1-\phi_1(a))(2\alpha E_2(t,a,v_5))-\gamma_1I_{MILD}(t,a,v_5)+2\psi I_{MILD}(t,a,v_4)$   
$\frac{dI_{CASE,0}(t,a,v_5)}{dt}=\phi_1(a)(2\alpha E_2(t,a,v_5))-2\gamma_2I_{CASE,0}(t,a,v_5)+2\psi I_{CASE,0}(t,a,v_4)$   
$\frac{dI_{CASE,1}(t,a,v_5)}{dt}=2\gamma_2I_{CASE,0}(t,a,v_5)-2\gamma_2I_{CASE,1}(t,a,v_5)+2\psi I_{CASE,1}(t,a,v_4)$   $\frac{dI_{HOSPITAL,0}(t,a,v_5,0,0)}{dt}=(1-\delta(H))\mu(a)(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_5)-2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_5,0,0)+2\psi I_{HOSPITAL,0}(t,a,v_4,0,0)$   $\frac{dI_{HOSPITAL,1}(t,a,v_5,0,0)}{dt}=2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_5,0,0)-2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_5,0,0)+2\psi I_{HOSPITAL,1}(t,a,v_4,0,0)$   $\frac{dI_{HOSPITAL,0}(t,a,v_5,1,0)}{dt}=\delta(H)\mu(a)(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_5)-2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_5,1,0)+2\psi I_{HOSPITAL,0}(t,a,v_3,1,0)$   $\frac{dI_{HOSPITAL,1}(t,a,v_5,1,0)}{dt}=2\gamma_{3,0}I_{HOSPITAL,0}(t,a,v_5,1,0)-2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_5,1,0)+2\psi I_{HOSPITAL,1}(t,a,v_4,1,0)$   $\frac{dI_{HOSPITAL,0}(t,a,v_5,0,1)}{dt}=(1-\delta(H))(1-\mu(a))(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_5)-2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_5,0,1)+2\psi I_{HOSPITAL,0}(t,a,v_4,0,1)$   $\frac{dI_{HOSPITAL,1}(t,a,v_5,0,1)}{dt}=2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_5,0,1)-2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_5,0,1)+2\psi I_{HOSPITAL,1}(t,a,v_4,0,1)$   $\frac{dI_{HOSPITAL,0}(t,a,v_5,1,1)}{dt}=\delta(H)(1-\mu(a))(1-\phi_2(a))2\gamma_2I_{CASE,1}(t,a,v_5)-2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_5,1,1)+2\psi I_{HOSPITAL,0}(t,a,v_4,1,1)$   $\frac{dI_{HOSPITAL,1}(t,a,v_5,1,1)}{dt}=2\gamma_{3,1}I_{HOSPITAL,0}(t,a,v_5,1,1)-2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_5,1,1)+2\psi I_{HOSPITAL,1}(t,a,v_4,1,1)$   $\frac{dI_{ICU,0}(t,a,v_5,0,0)}{dt}=(1-\delta(ICU))\mu(a)\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_5)-2\gamma_{4,0}I_{ICU,0}(t,a,v_5,0,0)+2\psi I_{ICU,0}(t,a,v_4,0,0)$   $\frac{dI_{ICU,1}(t,a,v_5,0,0)}{dt}=2\gamma_{4,0}I_{ICU,0}(t,a,v_5,0,0)-2\gamma_{4,0}I_{ICU,1}(t,a,v_5,0,0)+2\psi I_{ICU,1}(t,a,v_4,0,0)$   $\frac{dI_{ICU,0}(t,a,v_5,1,0)}{dt}=\delta(ICU)\mu(a)\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_5)-2\gamma_{4,0}I_{ICU,0}(t,a,v_5,1,0)+2\psi I_{ICU,0}(t,a,v_4,1,0)$   $\frac{dI_{ICU,1}(t,a,v_5,1,0)}{dt}=2\gamma_{4,0}I_{ICU,0}(t,a,v_5,1,0)-2\gamma_{4,0}I_{ICU,1}(t,a,v_5,1,0)+2\psi I_{ICU,1}(t,a,v_4,1,0)$   $\frac{dI_{ICU,0}(t,a,v_5,0,1)}{dt}=(1-\delta(ICU))(1-\mu(a))\phi_2(a)2\gamma_2I_{CASE,1}(t,v_5,a)-2\gamma_{4,1}I_{ICU,0}(t,a,v_5,0,1)+2\psi I_{ICU,0}(t,a,v_4,0,1)$   $\frac{dI_{ICU,1}(t,a,v_5,0,1)}{dt}=2\gamma_{4,1}I_{ICU,0}(t,a,v_5,0,1)-2\gamma_{4,1}I_{ICU,1}(t,a,v_5,0,1)+2\psi I_{ICU,1}(t,a,v_4,0,1)$   $\frac{dI_{ICU,0}(t,a,v_5,1,1)}{dt}=\delta(ICU)(1-\mu(a))\phi_2(a)2\gamma_2I_{CASE,1}(t,a,v_5)-2\gamma_{4,1}I_{ICU,0}(t,a,v_5,1,1)+2\psi I_{ICU,0}(t,a,v_4,1,1)$   $\frac{dI_{ICU,1}(t,a,v_5,1,1)}{dt}=2\gamma_{4,1}I_{ICU,0}(t,a,v_5,1,1)-2\gamma_{4,1}I_{ICU,1}(t,a,v_5,1,1)+2\psi I_{ICU,1}(t,a,v_4,1,1)$   $\frac{dI_{REC,0}(t,a,v_5)}{dt}=2\gamma_{4,1}I_{ICU,1}(t,a,v_5,0,1)+2\gamma_{4,1}I_{ICU,1}(t,a,v_5,1,1)-2\gamma_5I_{REC,0}(t,a,v_5)+2\psi I_{REC,0}(t,a,v_4)$   
$\frac{dI_{REC,1}(t,a,v_5)}{dt}=2\gamma_5I_{REC,0}(t,a,v_5)-2\gamma_5I_{REC,1}(t,a,v_5)+2\psi I_{REC,1}(t,a,v_4)$   $\frac{dR_1(t,a,v_5)}{dt}=\gamma_1I_{MILD}(t,a,v_5)+2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_5,0,1)+2\gamma_{3,1}I_{HOSPITAL,1}(t,a,v_5,1,1)+2\gamma_5I_{REC,1}(t,a,v_5)+2\gamma_{4,1}I_{ICU,1}(t,a,v_5,0,1)+2\gamma_{4,1}I_{ICU,1}(t,a,v_5,1,1)-2\rho R_1(t,a,v_5)+2\psi R_1(t,a,v_4)$   
$\frac{dR_2(t,a,v_5)}{dt}=2\rho R_1(t,a,v_5)-2\rho R_2(t,a,v_5)+2\psi R_2(t,a,v_4)$   $\frac{dD(t,a,v_5)}{dt}=2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_5,0,0)+2\gamma_{3,0}I_{HOSPITAL,1}(t,a,v_5,1,0)+2\gamma_{4,0}I_{ICU,1}(t,a,v_5,0,0)+2\gamma_{4,0}I_{ICU,1}(t,a,v_5,1,0)$

