## Automatically generated by odin - do not edit
.vaccine <- odin:::odin_c_class("vaccine", list(get_internal = "vaccine_get_internal", finalise = "vaccine_finalise", create = "vaccine_create", initmod_desolve = "vaccine_initmod_desolve", contents = "vaccine_contents", set_user = "vaccine_set_user", metadata = "vaccine_metadata", initial_conditions = "vaccine_initial_conditions", rhs = "vaccine_rhs", rhs_dde = "vaccine_rhs_dde", rhs_desolve = "vaccine_rhs_desolve", output = "vaccine_output_dde", rhs_r = "vaccine_rhs_r"), c("beta_set", "D_0", "dt", "E1_0", "E2_0", "gamma_E", "gamma_get_mv_die", "gamma_get_mv_survive", "gamma_get_ox_die", "gamma_get_ox_survive", "gamma_ICase", "gamma_IMild", "gamma_not_get_mv_die", "gamma_not_get_mv_survive", "gamma_not_get_ox_die", "gamma_not_get_ox_survive", "gamma_R", "gamma_rec", "gamma_vaccine", "ICase1_0", "ICase2_0", "IMild_0", "IMVGetDie1_0", "IMVGetDie2_0", "IMVGetLive1_0", "IMVGetLive2_0", "IMVNotGetDie1_0", "IMVNotGetDie2_0", "IMVNotGetLive1_0", "IMVNotGetLive2_0", "IOxGetDie1_0", "IOxGetDie2_0", "IOxGetLive1_0", "IOxGetLive2_0", "IOxNotGetDie1_0", "IOxNotGetDie2_0", "IOxNotGetLive1_0", "IOxNotGetLive2_0", "IRec1_0", "IRec2_0", "mix_mat_set", "N_age", "N_vaccine", "R1_0", "R2_0", "S_0", "tt_beta", "tt_matrix", "vaccination_target", "vaccine_efficacy_infection"), list(discrete = FALSE, has_array = TRUE, has_output = TRUE, has_user = TRUE, has_delay = FALSE, has_interpolate = TRUE, has_stochastic = FALSE, has_include = FALSE, initial_time_dependent = FALSE), "nimue", "odin/vaccine.json", TRUE)
vaccine <- structure(function (beta_set, D_0, dt, E1_0, E2_0, gamma_E, gamma_get_mv_die,
    gamma_get_mv_survive, gamma_get_ox_die, gamma_get_ox_survive,
    gamma_ICase, gamma_IMild, gamma_not_get_mv_die, gamma_not_get_mv_survive,
    gamma_not_get_ox_die, gamma_not_get_ox_survive, gamma_R,
    gamma_rec, gamma_vaccine, ICase1_0, ICase2_0, IMild_0, IMVGetDie1_0,
    IMVGetDie2_0, IMVGetLive1_0, IMVGetLive2_0, IMVNotGetDie1_0,
    IMVNotGetDie2_0, IMVNotGetLive1_0, IMVNotGetLive2_0, IOxGetDie1_0,
    IOxGetDie2_0, IOxGetLive1_0, IOxGetLive2_0, IOxNotGetDie1_0,
    IOxNotGetDie2_0, IOxNotGetLive1_0, IOxNotGetLive2_0, IRec1_0,
    IRec2_0, mix_mat_set, N_age, N_vaccine, R1_0, R2_0, S_0,
    tt_beta, tt_matrix, vaccination_target, vaccine_efficacy_infection,
    user = list(beta_set = beta_set, D_0 = D_0, dt = dt, E1_0 = E1_0,
        E2_0 = E2_0, gamma_E = gamma_E, gamma_get_mv_die = gamma_get_mv_die,
        gamma_get_mv_survive = gamma_get_mv_survive, gamma_get_ox_die = gamma_get_ox_die,
        gamma_get_ox_survive = gamma_get_ox_survive, gamma_ICase = gamma_ICase,
        gamma_IMild = gamma_IMild, gamma_not_get_mv_die = gamma_not_get_mv_die,
        gamma_not_get_mv_survive = gamma_not_get_mv_survive,
        gamma_not_get_ox_die = gamma_not_get_ox_die, gamma_not_get_ox_survive = gamma_not_get_ox_survive,
        gamma_R = gamma_R, gamma_rec = gamma_rec, gamma_vaccine = gamma_vaccine,
        ICase1_0 = ICase1_0, ICase2_0 = ICase2_0, IMild_0 = IMild_0,
        IMVGetDie1_0 = IMVGetDie1_0, IMVGetDie2_0 = IMVGetDie2_0,
        IMVGetLive1_0 = IMVGetLive1_0, IMVGetLive2_0 = IMVGetLive2_0,
        IMVNotGetDie1_0 = IMVNotGetDie1_0, IMVNotGetDie2_0 = IMVNotGetDie2_0,
        IMVNotGetLive1_0 = IMVNotGetLive1_0, IMVNotGetLive2_0 = IMVNotGetLive2_0,
        IOxGetDie1_0 = IOxGetDie1_0, IOxGetDie2_0 = IOxGetDie2_0,
        IOxGetLive1_0 = IOxGetLive1_0, IOxGetLive2_0 = IOxGetLive2_0,
        IOxNotGetDie1_0 = IOxNotGetDie1_0, IOxNotGetDie2_0 = IOxNotGetDie2_0,
        IOxNotGetLive1_0 = IOxNotGetLive1_0, IOxNotGetLive2_0 = IOxNotGetLive2_0,
        IRec1_0 = IRec1_0, IRec2_0 = IRec2_0, mix_mat_set = mix_mat_set,
        N_age = N_age, N_vaccine = N_vaccine, R1_0 = R1_0, R2_0 = R2_0,
        S_0 = S_0, tt_beta = tt_beta, tt_matrix = tt_matrix,
        vaccination_target = vaccination_target, vaccine_efficacy_infection = vaccine_efficacy_infection),
    unused_user_action = NULL, use_dde = FALSE)
{
    .vaccine$new(user, unused_user_action, use_dde)
}, ir = "odin/vaccine.json", class = "odin_generator")
class(vaccine) <- "odin_generator"
attr(vaccine, "ir") <- .vaccine$public_fields$ir
